# Generated by Django 5.0.1 on 2024-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowlog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
