# Generated by Django 5.0.1 on 2024-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0002_bookborrowlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='regular', max_length=50),
        ),
    ]
