# Generated by Django 5.0.1 on 2024-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0004_user_overduecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'musics',
                'unique_together': {('code', 'name')},
            },
        ),
    ]
