# Generated by Django 5.0.1 on 2024-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0005_music'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='music',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='music',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
