# Generated by Django 5.0.1 on 2024-01-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
