# Generated by Django 5.0.1 on 2024-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0003_alter_book_created_alter_book_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
