# Generated by Django 5.0.1 on 2024-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0004_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowlog',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('suspended', 'Duspended')], default='regular', max_length=50),
        ),
    ]
