# Generated by Django 5.0.1 on 2024-02-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0006_remove_bookborrowlog_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='log',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='lib_api.bookborrowlog'),
        ),
    ]
