# Generated by Django 5.0.1 on 2024-01-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_api', '0003_config_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='fine',
            new_name='total_fine',
        ),
        migrations.CreateModel(
            name='BookBorrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.PositiveIntegerField(default=0)),
                ('book_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib_api.book')),
                ('borrowk_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib_api.borrow')),
                ('config_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib_api.config')),
            ],
            options={
                'db_table': 'book_borrow_log',
            },
        ),
    ]
